# map_type: costmap

# obstacle_range: 4.0
# raytrace_range: 4.0
# #footprint: [[-0.1, -0.1], [-0.1, 0.1], [0.1, 0.1], [0.1, -0.1]]
# robot_radius: 0.4
# inflation_radius: 0.5

# observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: $(arg laser_frame), data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true}

robot_radius: 0.4
footprint_padding: 0.0

transform_tolerance: 0.5

always_send_full_costmap: true

obstacle_layer:
  enabled: true
  obstacle_range: 3.0
  raytrace_range: 4.0
  track_unknown_space: true
  combination_method: 1

  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    { data_type: LaserScan, topic: $(arg scan), marking: true, clearing: true, inf_is_valid: true }

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius: 0.1 # max. distance from an obstacle at which costs are incurred for planning paths (default: 0.55)

static_layer:
  enabled: true
  map_topic: "/map"
